import { MenuItem } from './types';

export const initialMenuData: Omit<MenuItem, 'createdAt' | 'updatedAt'>[] = [
  // 台灣原茶 (Taiwan Original Tea)
  {
    id: 'taiwan-1',
    name: '手採阿里山金萱',
    englishName: 'Hand Picked Alishan Jinxuan Tea',
    category: '台灣原茶',
    priceM: null,
    priceL: 40,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '蘭花 奶油香 茉莉花 (特等獎茶師監製•溯源保證)',
    tags: ['特等獎茶師'],
    onSale: true,
  },
  {
    id: 'taiwan-2',
    name: '名間鄉冬片仔',
    englishName: 'Winter Tea',
    category: '台灣原茶',
    priceM: null,
    priceL: 35,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '花香 奶油香 堅果 (招牌必喝)',
    tags: ['招牌必喝'],
    onSale: true,
  },
  {
    id: 'taiwan-3',
    name: '台茶十八號•紅玉',
    englishName: 'Ruby Black Tea',
    category: '台灣原茶',
    priceM: null,
    priceL: 35,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '薄荷 肉桂 荔枝 (招牌必喝)',
    tags: ['招牌必喝'],
    onSale: true,
  },
  {
    id: 'taiwan-4',
    name: '碧螺春•綠',
    englishName: 'Biluochun Green Tea',
    category: '台灣原茶',
    priceM: null,
    priceL: 30,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '海苔香 豌豆香',
    tags: [],
    onSale: true,
  },
  {
    id: 'taiwan-5',
    name: '金萱烏龍',
    englishName: 'Jinxuan Oolong Tea',
    category: '台灣原茶',
    priceM: null,
    priceL: 30,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '焙米香 蜂蜜香',
    tags: [],
    onSale: true,
  },
  {
    id: 'taiwan-6',
    name: '著涎金萱紅',
    englishName: 'Jinxuan Black Tea',
    category: '台灣原茶',
    priceM: null,
    priceL: 30,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '蜜糖香 莓果香',
    tags: [],
    onSale: true,
  },

  // 朵朵與莎莎 (Cheesy Cloud & Smoothie)
  {
    id: 'cheesy-1',
    name: '金萱烏龍朵朵',
    englishName: 'Cheese Sause on Jinxuan Oolong Tea',
    category: '朵朵與莎莎',
    priceM: null,
    priceL: 55,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '原茶加朵朵，使用整塊乳酪起司與法國愛樂薇鮮奶油調配',
    tags: ['朵朵奶蓋'],
    onSale: true,
  },
  {
    id: 'cheesy-2',
    name: '紅玉朵朵',
    englishName: 'Cheese Sause on Ruby Black Tea',
    category: '朵朵與莎莎',
    priceM: null,
    priceL: 60,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '原茶加朵朵，極致鹹甜起司奶蓋',
    tags: ['朵朵奶蓋'],
    onSale: true,
  },
  {
    id: 'cheesy-3',
    name: '可可脆片莎莎',
    englishName: 'Cocoa Cereal Smoothie',
    category: '朵朵與莎莎',
    priceM: null,
    priceL: 110,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '純冰沙、甜度固定。使用法國歌劇可可粉',
    tags: ['甜度固定', '冰沙'],
    onSale: true,
  },
  {
    id: 'cheesy-4',
    name: '可可脆片朵朵',
    englishName: 'Cheese Sause on Cocoa Cereal Smoothie',
    category: '朵朵與莎莎',
    priceM: null,
    priceL: 120,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '奶蓋冰沙、甜度固定。可可冰沙配上香濃起司奶蓋',
    tags: ['甜度固定', '奶蓋'],
    onSale: true,
  },

  // 柚香橙韻 (Orange & Grapefruit Tea)
  {
    id: 'orange-1',
    name: '柚香金萱',
    englishName: 'Grapefruit Juice Mixed Jinxuan Oolong Tea',
    category: '柚香橙韻',
    priceM: null,
    priceL: 55,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '葡萄柚珍貴原汁與清甜金萱烏龍調和',
    tags: [],
    onSale: true,
  },
  {
    id: 'orange-2',
    name: '柚粒金萱',
    englishName: 'Grapefruit Pulp & Juice Mixed Jinxuan Oolong Tea',
    category: '柚香橙韻',
    priceM: null,
    priceL: 65,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '葡萄柚果粒與鮮美金萱烏龍的雙重滋味',
    tags: [],
    onSale: true,
  },
  {
    id: 'orange-3',
    name: '柚粒多多',
    englishName: 'Grapefruit Pulp & Juice Mixed Yakult',
    category: '柚香橙韻',
    priceM: null,
    priceL: 70,
    isRecommended: true,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '滿滿葡萄柚果粒，搭配兩瓶養樂多',
    tags: ['推薦'],
    onSale: true,
  },
  {
    id: 'orange-4',
    name: '鮮橙冬片',
    englishName: 'Orange Juice Mixed Winter Tea',
    category: '柚香橙韻',
    priceM: null,
    priceL: 60,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '新鮮柳橙汁與招牌冬片仔茶的絕妙結合',
    tags: [],
    onSale: true,
  },
  {
    id: 'orange-5',
    name: '鮮橙香檸水果茶',
    englishName: 'Lemon & Orange Juice Mixed Biluochun Green Tea',
    category: '柚香橙韻',
    priceM: null,
    priceL: 70,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '清爽香檸、鮮榨柳橙與碧螺春綠茶',
    tags: [],
    onSale: true,
  },
  {
    id: 'orange-6',
    name: '鮮橙多多',
    englishName: 'Orange Juice Mixed Yakult',
    category: '柚香橙韻',
    priceM: null,
    priceL: 75,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '柳橙原汁，加上香甜養樂多',
    tags: [],
    onSale: true,
  },

  // 水果調飲 (Fresh Juice Tea)
  {
    id: 'fruit-1',
    name: '鳳梨金萱紅',
    englishName: 'Jinxuan Black Tea Mixed Pineapple Juice',
    category: '水果調飲',
    priceM: null,
    priceL: 55,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '古早味鳳梨醬與著涎金萱紅茶，甜度固定',
    tags: ['甜度固定'],
    onSale: true,
  },
  {
    id: 'fruit-2',
    name: '檸檬冬片仔',
    englishName: 'Winter Tea Mixed Lemon Juice',
    category: '水果調飲',
    priceM: null,
    priceL: 50,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '新鮮榨檸檬原汁與冬片仔，可做溫熱飲',
    tags: [],
    onSale: true,
  },
  {
    id: 'fruit-3',
    name: '百香冬片仔',
    englishName: 'Winter Tea Mixed Passion Fruit Juice',
    category: '水果調飲',
    priceM: null,
    priceL: 50,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '新鮮百香果原汁與冬片仔，可做溫熱飲',
    tags: [],
    onSale: true,
  },
  {
    id: 'fruit-4',
    name: '檸檬梅綠',
    englishName: 'Biluochun Green Tea Mixed Lemon Juice & Plum',
    category: '水果調飲',
    priceM: null,
    priceL: 50,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '碧螺春綠茶搭配新鮮檸檬與特製梅蜜',
    tags: [],
    onSale: true,
  },
  {
    id: 'fruit-5',
    name: '桑莓紅玉',
    englishName: 'Mulberry Juice Mixed Ruby Black Tea with Sweet Agar Jelly',
    category: '水果調飲',
    priceM: null,
    priceL: 60,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '酸甜桑椹果汁搭配紅玉紅茶與香Q寒天',
    tags: [],
    onSale: true,
  },
  {
    id: 'fruit-6',
    name: '桑莓鮮奶',
    englishName: 'Mulberry Juice Mixed Fresh Milk with Sweet Agar Jelly',
    category: '水果調飲',
    priceM: 65,
    priceL: 85,
    isRecommended: true,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '鮮甜美味桑椹原汁、初鹿鮮乳與香Q寒天',
    tags: ['推薦'],
    onSale: true,
  },
  {
    id: 'fruit-7',
    name: '百香•珍椰',
    englishName: 'Passion Fruit with Pearl & Coconut Jelly',
    category: '水果調飲',
    priceM: null,
    priceL: 55,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '酸甜百香果茶配上滿滿的珍珠與椰果',
    tags: [],
    onSale: true,
  },

  // 香醇鮮乳 (Latte)
  {
    id: 'latte-1',
    name: '玉霞紅茶拿鐵',
    englishName: 'Ruby Black Tea Latte',
    category: '香醇鮮乳',
    priceM: 45,
    priceL: 60,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '茶味醇厚的紅茶特調拿鐵，口感滑順',
    tags: [],
    onSale: true,
  },
  {
    id: 'latte-2',
    name: '金萱烏龍拿鐵',
    englishName: 'Jinxuan Oolong Tea Latte',
    category: '香醇鮮乳',
    priceM: 45,
    priceL: 60,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '米焙香金萱烏龍加入香醇鮮奶',
    tags: ['推薦'],
    onSale: true,
  },
  {
    id: 'latte-3',
    name: '蜜香紅茶拿鐵',
    englishName: 'Jinxuan Black Tea Latte',
    category: '香醇鮮乳',
    priceM: 45,
    priceL: 60,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '著涎金萱紅特調，散發迷人蜜香風味',
    tags: [],
    onSale: true,
  },
  {
    id: 'latte-4',
    name: '珍珠紅茶拿鐵',
    englishName: 'Ruby Black Tea Latte with Pearl',
    category: '香醇鮮乳',
    priceM: 45,
    priceL: 60,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '紅茶拿鐵配上招牌 Q 彈珍珠',
    tags: [],
    onSale: true,
  },
  {
    id: 'latte-5',
    name: '珍椰•紅茶拿鐵',
    englishName: 'Ruby Black Tea Latte with Pearl & Coconut Jelly',
    category: '香醇鮮乳',
    priceM: 50,
    priceL: 65,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '滿足感十足！珍珠與椰果雙料紅茶拿鐵',
    tags: ['推薦'],
    onSale: true,
  },
  {
    id: 'latte-6',
    name: '珍椰•紅玉拿鐵',
    englishName: 'Ruby Black Tea Latte with Pearl & Coconut Jelly',
    category: '香醇鮮乳',
    priceM: 50,
    priceL: 65,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '紅玉紅茶與鮮乳、珍珠、椰果的完美演出',
    tags: [],
    onSale: true,
  },
  {
    id: 'latte-7',
    name: '大人的可可拿鐵',
    englishName: 'Brown Sugar Mixed Cocoa Latte',
    category: '香醇鮮乳',
    priceM: 75,
    priceL: 90,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '甜度固定，法國歌劇可可與濃郁黑糖鮮乳',
    tags: ['甜度固定'],
    onSale: true,
  },
  {
    id: 'latte-8',
    name: '黑糖鮮奶珍珠',
    englishName: 'Brown Sugar Milk with Pearl',
    category: '香醇鮮乳',
    priceM: 65,
    priceL: 85,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: true,
    description: '甜度固定，手工精心炒製黑糖與 Q 彈珍珠。無咖啡因',
    tags: ['甜度固定', '無咖啡因'],
    onSale: true,
  },

  // 醇奶特調 (Non-Dairy Creamer)
  {
    id: 'creamer-1',
    name: '玉霞醇奶茶',
    englishName: 'Ruby Black Milk Tea',
    category: '醇奶特調',
    priceM: 35,
    priceL: 50,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '特調手搖經典奶茶，奶香醇厚',
    tags: [],
    onSale: true,
  },
  {
    id: 'creamer-2',
    name: '珍珠醇奶茶',
    englishName: 'Ruby Black Milk Tea with Pearl',
    category: '醇奶特調',
    priceM: 35,
    priceL: 50,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '奶香醇厚的珍珠奶茶',
    tags: [],
    onSale: true,
  },
  {
    id: 'creamer-3',
    name: '杏仁凍醇奶茶',
    englishName: 'Ruby Black Milk Tea with Almond Jelly',
    category: '醇奶特調',
    priceM: 40,
    priceL: 55,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '滑嫩杏仁凍與醇厚奶茶，絕配口感',
    tags: [],
    onSale: true,
  },
  {
    id: 'creamer-4',
    name: '珍椰•醇奶茶',
    englishName: 'Ruby Black Milk Tea with Pearl & Coconut Jelly',
    category: '醇奶特調',
    priceM: 40,
    priceL: 55,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '招牌珍珠與清脆椰果雙拼奶茶',
    tags: ['推薦'],
    onSale: true,
  },

  // 原茶調飲 (Tea Cocktail)
  {
    id: 'cocktail-1',
    name: '杏仁凍冬片仔',
    englishName: 'Winter Tea with Almond Jelly',
    category: '原茶調飲',
    priceM: null,
    priceL: 50,
    isRecommended: true,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '古早味杏仁凍搭配清新冬片仔原茶',
    tags: ['推薦'],
    onSale: true,
  },
  {
    id: 'cocktail-2',
    name: '養樂多綠茶',
    englishName: 'Biluochun Green Tea Mixed Yakult',
    category: '原茶調飲',
    priceM: null,
    priceL: 50,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: false,
    description: '酸甜養樂多與鮮活碧螺春綠茶',
    tags: [],
    onSale: true,
  },
  {
    id: 'cocktail-3',
    name: '春枝梅綠',
    englishName: 'Biluochun Green Tea with Plum',
    category: '原茶調飲',
    priceM: null,
    priceL: 45,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '精選青梅與香氣明亮的碧螺春綠茶，酸甜生津',
    tags: ['推薦'],
    onSale: true,
  },
  {
    id: 'cocktail-4',
    name: '珍椰•金萱烏龍',
    englishName: 'Jinxuan Oolong Tea with Pearl & Coconut Jelly',
    category: '原茶調飲',
    priceM: null,
    priceL: 45,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: false,
    description: '金萱烏龍搭配珍珠與椰果的豐富口感組合',
    tags: ['推薦'],
    onSale: true,
  },

  // 不失眠 (Decaffeine)
  {
    id: 'decaf-1',
    name: '不苦蕎麥茶',
    englishName: 'Buckwheat Tea',
    category: '不失眠',
    priceM: null,
    priceL: 40,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: true,
    description: '花蓮玉里黄金蕎麥，無咖啡因，溫和香郁',
    tags: ['無咖啡因'],
    onSale: true,
  },
  {
    id: 'decaf-2',
    name: '蕎麥冬露',
    englishName: 'Buckwheat Tea Mixed Wintermelon Drink',
    category: '不失眠',
    priceM: null,
    priceL: 50,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: true,
    description: '甜度固定，蕎麥茶遇上冬瓜露，甘甜解渴',
    tags: ['甜度固定', '無咖啡因'],
    onSale: true,
  },
  {
    id: 'decaf-3',
    name: '不苦蕎麥鮮奶',
    englishName: 'Buckwheat Tea Mixed Fresh Milk',
    category: '不失眠',
    priceM: null,
    priceL: 65,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: true,
    description: '純粹蕎麥與初鹿鮮乳相互輝映，無咖啡因',
    tags: ['無咖啡因'],
    onSale: true,
  },
  {
    id: 'decaf-4',
    name: '黃金菊花茶',
    englishName: 'Chrysanthemum Tea',
    category: '不失眠',
    priceM: null,
    priceL: 50,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: true,
    description: '苗栗銅鑼3-11月期間限定，安心契作，天然清香',
    tags: ['無咖啡因'],
    onSale: true,
  },
  {
    id: 'decaf-5',
    name: '菊花冬露',
    englishName: 'Chrysanthemum Tea Mixed Wintermelon Drink',
    category: '不失眠',
    priceM: null,
    priceL: 60,
    isRecommended: false,
    isHotPossible: true,
    isNoCaffeine: true,
    description: '限定菊花茶與冬瓜甜露的細緻風味',
    tags: ['無咖啡因'],
    onSale: true,
  },

  // 抱抱冬瓜 (Wintermelon Drink)
  {
    id: 'melon-1',
    name: '抱抱冬瓜露',
    englishName: 'Wintermelon Drink',
    category: '抱抱冬瓜',
    priceM: null,
    priceL: 35,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: true,
    description: '甜度固定，無添加石灰，傳統慢火熬煮',
    tags: ['甜度固定', '無咖啡因'],
    onSale: true,
  },
  {
    id: 'melon-2',
    name: '杏仁凍冬露',
    englishName: 'Wintermelon Drink with Almond Jelly',
    category: '抱抱冬瓜',
    priceM: null,
    priceL: 50,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: true,
    description: '香甜冬瓜露加入滑嫩的古早味杏仁凍',
    tags: ['無咖啡因'],
    onSale: true,
  },
  {
    id: 'melon-3',
    name: '冬露冬片仔',
    englishName: 'Wintermelon Drink Mixed Winter Tea',
    category: '抱抱冬瓜',
    priceM: null,
    priceL: 45,
    isRecommended: true,
    isHotPossible: true,
    isNoCaffeine: true,
    description: '冬瓜露與冬片仔原茶。半茶半瓜，獨特清甜',
    tags: ['無咖啡因'],
    onSale: true,
  },
  {
    id: 'melon-4',
    name: '檸檬冬露',
    englishName: 'Wintermelon Drink Mixed Lemon Juice',
    category: '抱抱冬瓜',
    priceM: null,
    priceL: 50,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: true,
    description: '新鮮檸檬配慢熬瓜甜，酸香生津',
    tags: ['無咖啡因'],
    onSale: true,
  },
  {
    id: 'melon-5',
    name: '冬露鮮奶',
    englishName: 'Wintermelon Drink Mixed Fresh Milk',
    category: '抱抱冬瓜',
    priceM: null,
    priceL: 65,
    isRecommended: false,
    isHotPossible: false,
    isNoCaffeine: true,
    description: '鮮牛乳衝入甘醇冬瓜露，甜潤迷人',
    tags: ['無咖啡因'],
    onSale: true,
  }
];
export const TOPPINGS = [
  { name: '朵朵奶蓋', price: 25 },
  { name: '珍珠', price: 10 },
  { name: '杏仁凍', price: 15 },
  { name: '椰果', price: 15 },
  { name: '珍珠+椰果', price: 15 },
  { name: '原味寒天', price: 15 }
];
